feat: lora
stochasticai/xturing pull request #111
Opened 2023-04-05 15:40 UTC by Toan-Do

- Replace Peft and re-implement LoRA.

2023-04-05 16:06 UTC, sarthaklangde requested changes

2023-04-05 16:06 UTC, sarthaklangde commented on src/xturing/engines/gptj_engine.py
> +        tokenizer = AutoTokenizer.from_pretrained(
This is not OK!

2023-04-05 17:08 UTC, sarthaklangde approved these changes

2023-04-05 17:11 UTC, sarthaklangde approved these changes

2023-04-06 13:12 UTC, MarcosRiveraMartinez approved these changes

2023-04-06 13:14 UTC, merged